# options: 'on'/'off'
ev_guardian_yielding:
  name: "EV Guardian: Yielding"
  icon: mdi:ev-station

# options: 'on'/'off'
ev_guardian_quiet:
  name: "EV Guardian: House Quiet"
  icon: mdi:home-silent
