# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage
  dashboards:
    managed-ev:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Capacity Guardian
      icon: mdi:car-electric

automation: !include_dir_list src/automations
script: !include_dir_merge_named src/scripts
scene: !include scenes.yaml

# homeassistant.packages allow a single YAML file to define multiple domains together
homeassistant:
  packages:
    # state for the guardian script (but NOT name-spacing!)
    guardian_state: !include helpers.yaml
