# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Enable YAML mode for dashboards
lovelace:
  mode: storage
  dashboards:
    managed-ev:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Capacity Guardian
      icon: mdi:car-electric

automation: !include_dir_list automations
script: !include_dir_merge_named scripts

# saved snapshots of specific states for multiple devices or entities (like lights, media players, and covers)
# that allow you to restore a precise configuration all at once
scene: !include scenes.yaml

# ecoflow modbus integration
modbus: !include modbus/ecoflow.yaml

# homeassistant.packages allow a single YAML file to define multiple domains together
homeassistant:
  packages:
    # state for the guardian script (key is unused)
    guardian_state: !include helpers/helpers.yaml
